config/routes.rb
Rails.application.routes.draw do
  
  resources :questions

  get 'about' => 'questionme#about'

  
  root to: 'questionme#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers 
  has_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    belongs_to :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questionme_controller.rb
class QuestionmeController < ApplicationController
  def index

  end

  def about
  end

  def contact
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  
  def index
       @opened = Question.where(status: 'Open').order('id ASC')  
       @solved = Question.where(status: 'Solved').order('id DESC').take(3)
  end



  def show
    @questions = Question.find(params[:id])
    @answers = Question.find(params[:id]).answers
    @anyAnswers = Question.find(params[:id]).answers.exists?


  end




  def new
    @questions = Question.new
  end




  def create
    @questions = Question.new(params.require(:question).permit(:questions, :status))

    if @questions.save
      flash[:notice] = "Question was saved!"
      redirect_to questions_path
    else
      flash[:error] = "Coud not save your question."
      render :new
    end
  end




  def edit
    @questions = Question.find(params[:id])
    @answers = Question.find(params[:id]).answers

  end




  def update
    @questions = Question.find(params[:id])


    if @questions.update_attributes(params.require(:question).permit(:questions, :status))
      flash[:notice] = "Post was updated."
      redirect_to @questions
    else
      flash[:error] = "Could not update your question."
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questionme_helper.rb
module QuestionmeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuestionMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<ul>
<ul class="nav nav-tabs">
<li><%= link_to "QuestionMe", root_path %></li>
<li><%= link_to "About", about_path %></li>  
<li><%= link_to "My Questions", questions_path %></li>  

</ul>


<%= yield %>
</div>
</body>
</html>

app/views/questionme/about.html.erb
<h1>Questionme#about</h1>
<p>Find me in app/views/questionme/about.html.erb</p>

app/views/questionme/contact.html.erb
<h1>Questionme#contact</h1>
<p>Find me in app/views/questionme/contact.html.erb</p>

app/views/questionme/index.html.erb
<h1>Questionme#index</h1>
   

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>


  <%= form_for @questions do |f| %>

  <div class="form-group">
    <%= f.label :questions %>
    <%= f.text_field :questions, class: 'form-control', placeholder: @questions %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.text_field :status, class: 'form-control', placeholder: "Open" %>
  </div>

  <%= f.submit "Enter", class: 'btn btn-success' %>
<% end %>

app/views/questions/index.html.erb
<h2>Open Questions</h2>
<div class="media">
  <div class="media-body">
    <div class="media-heading">

        <% @opened.each do |q| %>
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title"><%= link_to q.questions, q %> &nbsp; &nbsp; &nbsp;<%= link_to "Edit", edit_question_path(q), align:"right" %></h3> 
          </div>
    <div class="panel-body">
        <p></p>
            
    </div>
  </div>

        <% end %>

    </div>  
  </div
</div>

<h2> Solved Questions</h2>
<div class="media">
  <div class="media-body">
    <div class="media-heading">
  
  <% @solved.each do |q| %>

  <div class="panel panel-success">
    <div class="panel-heading">
          <h3 class="panel-title"><%= link_to q.questions, q %></h3>
    </div>
    <div class="panel-body">
        Answer would go here 
    </div>
  </div>
  <% end %>

    </div>  
  </div
</div>


<%= @join %>

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>

  <%= form_for @questions do |f| %>

  <div class="form-group">
    <%= f.label :questions %>
    <%= f.text_field :questions, class: 'form-control', placeholder: "Enter a question for your mentor." %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.text_field :status, class: 'form-control', placeholder: "Open" %>
  </div>

  <%= f.label "Enter", class: 'btn btn-success' %>
<% end %>


<div class="form-group">
      <label for="disabledSelect">Disabled select menu</label>
      <select id="disabledSelect" class="form-control">
        <option>Disabled select</option>
      </select>
    </div>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

<p>Question: <%= @questions.questions %></p>
<p>Status: <%= @questions.status %></p>
<p>Answers:</p>

  <% if @anyAnswers == false %>
    <%= "No answers yet!" %>
  <% else %>
    <% @answers.each do |answer| %>
      <tr><td><%= answer.answers %></td></tr>
    <% end %>
  <% end %>
    